import type { Db } from '../db/pool.js';
import type {
  Application,
  CloudflareAccount,
  CloudflareZone,
  DnsRecord,
  HealthCheck,
  NpmExpectation,
  NpmInstance,
  ProxmoxInstance,
  Site,
  Tunnel,
  Workload,
} from '../domain/types.js';
import { TableRepo } from './sql.js';

/** All configuration tables, with their writable columns. */
export function createRepos(db: Db) {
  return {
    sites: new TableRepo<Site>(db, 'sites', ['code', 'name', 'description', 'designatedRole', 'hostsController'], 'code'),
    proxmox: new TableRepo<ProxmoxInstance>(db, 'proxmox_instances', [
      'siteId',
      'name',
      'baseUrl',
      'tokenId',
      'tokenSecretId',
      'tlsCaPem',
      'tlsInsecure',
    ]),
    npm: new TableRepo<NpmInstance>(db, 'npm_instances', ['siteId', 'name', 'baseUrl', 'identity', 'secretId', 'tlsCaPem', 'tlsInsecure']),
    cloudflareAccounts: new TableRepo<CloudflareAccount>(db, 'cloudflare_accounts', ['name', 'accountId', 'apiTokenSecretId', 'baseUrl']),
    zones: new TableRepo<CloudflareZone>(db, 'cloudflare_zones', ['cloudflareAccountId', 'zoneId', 'name'], 'name'),
    tunnels: new TableRepo<Tunnel>(db, 'tunnels', ['siteId', 'cloudflareAccountId', 'tunnelId', 'name']),
    applications: new TableRepo<Application>(
      db,
      'applications',
      ['slug', 'name', 'description', 'failoverPriority', 'maxReplicationAgeSeconds', 'activeSiteId', 'enabled'],
      'failover_priority, name',
    ),
    workloads: new TableRepo<Workload>(
      db,
      'workloads',
      [
        'applicationId',
        'siteId',
        'proxmoxInstanceId',
        'node',
        'vmid',
        'kind',
        'expectedName',
        'standbyState',
        'allowStart',
        'allowStop',
        'replicationSource',
        'replicationVmid',
        'backupStorage',
        'startOrder',
      ],
      'start_order, vmid',
    ),
    dnsRecords: new TableRepo<DnsRecord>(
      db,
      'dns_records',
      [
        'applicationId',
        'zoneId',
        'recordId',
        'name',
        'type',
        'primaryContent',
        'secondaryContent',
        'ttl',
        'proxied',
        'failoverPriority',
        'lastVerifiedAt',
      ],
      'failover_priority, name',
    ),
    npmExpectations: new TableRepo<NpmExpectation>(db, 'npm_expectations', [
      'applicationId',
      'siteId',
      'npmInstanceId',
      'proxyHostId',
      'domainNames',
      'forwardScheme',
      'forwardHost',
      'forwardPort',
      'requireSsl',
      'mustBeEnabled',
      'allowAutoEnable',
    ]),
    healthChecks: new TableRepo<HealthCheck>(
      db,
      'health_checks',
      [
        'name',
        'siteId',
        'applicationId',
        'category',
        'type',
        'path',
        'independenceGroup',
        'config',
        'intervalSeconds',
        'timeoutMs',
        'critical',
        'enabled',
      ],
      'name',
    ),
  };
}

export type Repos = ReturnType<typeof createRepos>;
